### ISSUE TITLE
WotLK update.

### ISSUE THREAD

**Issue by durlagdt** [Motrish/tbcprogress#1]
Good day.
Any chance for new EQDKP progression plugin for WotLK classic update?

**Comment by Motrish** [comment]
Will Push an Update in a few days. 
Now as my new guild ist completely organized via discord, I forgot the  eqdkp. (Sorry mates)
The implementation of heroic Progress is planed in a later Update ;)

**Comment by Motrish** [comment]
@durlagdt  I pushed a new plugin... https://github.com/Motrish/wotlkprogress
please test and give Feedback if there are any issues ;) 
need to change the images when its finished ;)

**Comment by durlagdt** [comment]
Tnx a lot.
Added Russian translation.
[russian.zip](https://github.com/Motrish/tbcprogress/files/9544215/russian.zip)

Additions needed:
May be some sort of 10/25 raid type selection;
Missed Vault of Archavon;
New background textures for raids (mentioned above).
